/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Text, TouchableOpacity} from 'react-native';

import ProgressView from 'rn-progress';
import styles, {progressWidth, progressHeight} from './styles';
const MAX_VALUE = 300;
export default class App extends Component<{}> {
  constructor(props) {
    super(props);
    this.renderCount = 0;
    this.progressValue = 0;
  }

  startProgress = () => {
    this.progressValue = 0;
    this.updateProgressBar();
  };

  updateProgressBar = () => {
    this.progressValue++;
    if (this.progressValue > MAX_VALUE) {
      this.progressValue = 0;
    } else {
      setTimeout(this.updateProgressBar, 20);
    }

    this.progressView.setNativeProps({
      total: MAX_VALUE,
      current: this.progressValue,
    });
  };

  renderProgressBar = () => {
    return (
      <ProgressView
        progressHeight={progressHeight}
        progressWidth={progressWidth}
        barColorCurrent="#f18326"
        barColorCurrent2="#fcc769"
        barColorTotal="#fce789"
        style={styles.progressStyle}
        ref={(progressView) => {
          this.progressView = progressView;
        }}
      />
    );
  };

  render() {
    console.log(`Render Called: ${this.renderCount++}`);

    return (
      <TouchableOpacity style={styles.container} onPress={this.startProgress}>
        <Text style={styles.welcome}>☆RnProgress example☆</Text>
        <Text style={styles.welcome}>Click to Start a Progress</Text>
        {this.renderProgressBar()}
      </TouchableOpacity>
    );
  }
}
